services:
  - type: web
    name: comedor-app-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/comedor-app-0.0.1-SNAPSHOT.jar
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
